name = "cf-location"
main = "src/index.js"
compatibility_date = "2024-04-03"

[vars]
# 管理員訪問密鑰 (必須使用 wrangler secret put ADMIN_KEY 設定，嚴禁寫死在設定檔中)
# ADMIN_KEY = "your_secret_key"

[[d1_databases]]
binding = "DB"
database_name = "ip-location-db"
database_id = "c8239f76-10c4-4ba0-8bbe-2c4897d5d982"

[triggers]
crons = ["0 0 * * *"] # 每天午夜執行資料清理
